// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evduyglauetjjdvcmayp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZHV5Z2xhdWV0ampkdmNtYXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzQxODIsImV4cCI6MjA1ODY1MDE4Mn0.vIi3M36RVHi1C7ktnsI7BZ5cdg4hJ4LjwZGlOpNEtoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);